# Generated by Django 4.2.6 on 2023-10-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_type',
            field=models.CharField(default='Others', max_length=200),
        ),
    ]
